spring.application.name=aluguel-equipamentos-api

spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5433/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false


app.admin-inicial.habilitado=${ADMIN_INICIAL_HABILITADO:false}
app.admin-inicial.nome=${ADMIN_INICIAL_NOME:}
app.admin-inicial.email=${ADMIN_INICIAL_EMAIL:}
app.admin-inicial.senha=${ADMIN_INICIAL_SENHA:}

app.jwt.emissor=aluguel-equipamentos-api
app.jwt.segredo=${JWT_SEGREDO:}
app.jwt.expiracao-minutos=${JWT_EXPIRACAO_MINUTOS:30}
