CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR(10) NOT NULL,
    nome_razao_social VARCHAR(150) NOT NULL,
    nome_fantasia VARCHAR(150),
    documento VARCHAR(14) NOT NULL,
    email VARCHAR(150) NOT NULL,
    telefone VARCHAR(11) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    logradouro VARCHAR(150) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    complemento VARCHAR(100),
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT uk_clientes_documento UNIQUE (documento),
    CONSTRAINT uk_clientes_email UNIQUE (email),
    CONSTRAINT ck_clientes_email_minusculo CHECK (email = LOWER(email)),
    CONSTRAINT ck_clientes_tipo CHECK (tipo IN ('PF', 'PJ')),
    CONSTRAINT ck_clientes_documento_numerico CHECK (documento ~ '^[0-9]+$'),
    CONSTRAINT ck_clientes_documento_tamanho CHECK ((tipo = 'PF' AND CHAR_LENGTH(documento) = 11) OR (tipo = 'PJ' AND CHAR_LENGTH(documento) = 14)),
    CONSTRAINT ck_clientes_nome_fantasia CHECK (tipo = 'PJ' OR nome_fantasia IS NULL),
    CONSTRAINT ck_clientes_telefone_numerico CHECK (telefone ~ '^[0-9]+$'),
    CONSTRAINT ck_clientes_telefone_tamanho CHECK (CHAR_LENGTH(telefone) IN (10, 11)),
    CONSTRAINT ck_clientes_cep_numerico CHECK (cep ~ '^[0-9]+$'),
    CONSTRAINT ck_clientes_cep_tamanho CHECK (CHAR_LENGTH(cep) = 8),
    CONSTRAINT ck_clientes_estado_maiusculo CHECK (estado = UPPER(estado)),
    CONSTRAINT ck_clientes_estado_valido
    CHECK (
        estado IN (
            'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF',
            'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA',
            'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS',
            'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
        )
    ),
    CONSTRAINT ck_clientes_nome_razao_social_nao_vazio CHECK (BTRIM(nome_razao_social) <> ''),
    CONSTRAINT ck_clientes_email_nao_vazio CHECK (BTRIM(email) <> ''),
    CONSTRAINT ck_clientes_logradouro_nao_vazio CHECK (BTRIM(logradouro) <> ''),
    CONSTRAINT ck_clientes_numero_nao_vazio CHECK (BTRIM(numero) <> ''),
    CONSTRAINT ck_clientes_bairro_nao_vazio CHECK (BTRIM(bairro) <> ''),
    CONSTRAINT ck_clientes_cidade_nao_vazia CHECK (BTRIM(cidade) <> ''),
    CONSTRAINT ck_clientes_estado_nao_vazio CHECK (BTRIM(estado) <> ''),
    CONSTRAINT ck_clientes_nome_fantasia_nao_vazio
    CHECK (
        nome_fantasia IS NULL
        OR BTRIM(nome_fantasia) <> ''
    ),
    CONSTRAINT ck_clientes_complemento_nao_vazio
    CHECK (
        complemento IS NULL
        OR BTRIM(complemento) <> ''
    ),
    CONSTRAINT ck_clientes_cep_nao_vazio
    CHECK (BTRIM(cep) <> '')
   );