CREATE TABLE equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    valor_diaria NUMERIC(10,2) NOT NULL,
    categoria_id BIGINT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_equipamentos PRIMARY KEY (id),
    CONSTRAINT fk_equipamentos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id)

);